services:
  db:
    image: postgres:18
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: rms_application_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql