quarkus.rest.path=/api
quarkus.datasource.devservices.enabled=false

# Database setting
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:root}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${DB_NAME:my_db}