quarkus.rest.path=/api
quarkus.datasource.devservices.enabled=false

# Database setting
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=${DB_USER:root}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/${DB_NAME:my_db}

# Enable CORS globally
quarkus.http.cors.enabled=true

# Allow frontend origin
quarkus.http.cors.origins=${FRONTEND_URL}

# Specify which methods are allowed
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS

# Specify which headers are allowed (essential for Auth or JSON content)
quarkus.http.cors.headers=accept, authorization, content-type, x-requested-with

# (Optional) How long the browser should cache the CORS preflight request
quarkus.http.cors.access-control-max-age=6H

# Signing (for token generation)
smallrye.jwt.sign.key.location=privateKey.pem

# Point to your public key for verification
mp.jwt.verify.publickey.location=publicKey.pem
mp.jwt.verify.issuer=http://rms-application-backend

quarkus.native.resources.includes=publicKey.pem

# Flyway
quarkus.flyway.migrate-at-start=true
quarkus.flyway.schemas=public
quarkus.flyway.out-of-order=true
quarkus.flyway.repair-at-start=true

quarkus.hibernate-orm.dialect=org.hibernate.dialect.PostgreSQLDialect
mp.orm.id-generation-strategy=identity
